def menu1(j) :
    print(" --------------------------------------- ")
    print("|                HIJAUAN                |")
    print(" --------------------------------------- ")
    print("| PENJELASAN :                          |")
    print("| Pakan utama ternak sapi yang berupa   |")
    print("| rumput. Dapat berupa rumput unggul,   |")
    print("| rumput lapangan, dan sebagian jenis   |")
    print("| leguminosa                            |")
    print("|                                       |")
    print("| RINCIAN :                             |")
    print("| Kebutuhan Pakan = 10% Berat Sapi (kg) |")
    print("| Hijauan = 60% Kebutuhan Pakan (kg)    |")
    print(" --------------------------------------- ")
    print("Referensi : http://sumbar.litbang.pertanian.go.id/index.php/info-tek/966-pakan-untuk-ternak-sapi-potong-2")
    if j == 0 :
        print("            https://distanpangan.baliprov.go.id/penyediaan-pakan-sapi-sepanjang-tahun/")
    elif j == 1 : 
        print("            https://dispertan.bantenprov.go.id/lama/read/artikel/276/Formula-Pakan-Ternak-Sapi-Perah-Praktis.html")

def menu2(x) :
    print(" --------------------------------------- ")
    print("|               KONSENTRAT              |")
    print(" --------------------------------------- ")
    print("| PENJELASAN :                          |")
    print("| Makanan penguat yang merupakan        |") 
    print("| campuran dari beberapa bahan untuk    |")
    print("| melengkapi kekurangan gizi dari       |")
    print("| hijauan. Terdiri dari bahan pakan     |")
    print("| dengan kandungan serat kasar rendah   |")
    print("| dan mudah dicerna. yang berasal dari  |")
    print("| biji - bijian, hasil limbah pertanian,|")
    print("| dan bahan berasal dari hewan seperti  |")
    print("| tepung ikan dan lain - lain           |")
    print("|                                       |")
    print("| RINCIAN :                             |")
    print("| Kebutuhan Pakan = 10% Berat Sapi (kg) |")
    print("| Konsentrat = 40% Kebutuhan Pakan (kg) |")
    print("|                                       |")
    if x == 0 :
        print("| Bungkil Kelapa =   10% Konsentrat (kg)|")
        print("| Bungkil Jagung =   30% Konsentrat (kg)|")
        print("| Dedak          = 54.8% Konsentrat (kg)|")
        print("| Mineral Mix    =  0.2% Konsentrat (kg)|")
        print("| Tepung Ikan    =  0.2% Konsentrat (kg)|")
        print(" --------------------------------------- ")
        print("Referensi : http://sumbar.litbang.pertanian.go.id/index.php/info-tek/966-pakan-untuk-ternak-sapi-potong-2")
        print("            https://dinpertanpangan.demakkab.go.id/?p=2884")
    elif x == 1 :
        print("| Bungkil Kelapa =  25% Konsentrat (kg)  |")
        print("| Bungkil Kacang =  20% Konsentrat (kg)  |")
        print("| Tepung Jagung  =  25% Konsentrat (kg)  |")
        print("| Dedak Padi     =  25% Konsentrat (kg)  |")
        print("| Ampas Tahu     =   1% Konsentrat (kg)  |")
        print("| Garam Dapur    =   1% Konsentrat (kg)  |")
        print("| Kapur          =   1% Konsentrat (kg)  |")
        print("| Tepung Tulang  =   1% Konsentrat (kg)  |")
        print(" --------------------------------------- ")
        print("Referensi : http://sumbar.litbang.pertanian.go.id/index.php/info-tek/966-pakan-untuk-ternak-sapi-potong-2")
        print("            https://dispertan.bantenprov.go.id/lama/read/artikel/276/Formula-Pakan-Ternak-Sapi-Perah-Praktis.html")
    

def menu3() :
    print(" --------------------------------------- ")
    print("|           VITAMIN & MINERAL           |")
    print(" --------------------------------------- ")
    print("| PENJELASAN :                          |")
    print("| Tambahan yang berguna untuk merangsang|")
    print("| pertumbuhan, mencegah penyakit, dan   |")
    print("| melengkapi ransum pakan ternak.       |")
    print("| Terdiri dari campuran vitamin dan     |")
    print("| mineral.                              |")
    print("|                                       |")
    print("| RINCIAN :                             |")
    print("| Kebutuhan Pakan = 10% Berat Sapi (kg) |")
    print("| Vit Mineral = 2% Kebutuhan Pakan (kg) |")
    print(" --------------------------------------- ")